"""4K stereo synthesis research prototypes with lazy public exports."""

_LAZY_EXPORTS = {
    "DepthRuntimeConfig": ("adapter", "DepthRuntimeConfig"),
    "StereoLabDepthRuntimeConfig": ("adapter", "StereoLabDepthRuntimeConfig"),
    "StereoLabRuntimeConfig": ("adapter", "StereoLabRuntimeConfig"),
    "StereoRuntimeConfig": ("adapter", "StereoRuntimeConfig"),
    "depth_provider_config_from_runtime": ("adapter", "depth_provider_config_from_runtime"),
    "preset_for_runtime_mode": ("adapter", "preset_for_runtime_mode"),
    "runtime_frame_contract": ("adapter", "runtime_frame_contract"),
    "runtime_config_from_d2s_settings": ("adapter", "runtime_config_from_d2s_settings"),
    "stereo_config_from_runtime": ("adapter", "stereo_config_from_runtime"),
    "DepthModelSpec": ("model_registry", "DepthModelSpec"),
    "ModelRegistry": ("model_registry", "ModelRegistry"),
    "resolve_model_dir": ("model_registry", "resolve_model_dir"),
    "ModelArtifactPaths": ("model_artifacts", "ModelArtifactPaths"),
    "PreparedModelArtifacts": ("model_artifacts", "PreparedModelArtifacts"),
    "artifact_paths_for_model": ("model_artifacts", "artifact_paths_for_model"),
    "ensure_model_downloaded": ("model_artifacts", "ensure_model_downloaded"),
    "ensure_onnx_exported": ("model_artifacts", "ensure_onnx_exported"),
    "ensure_tensorrt_engine": ("model_artifacts", "ensure_tensorrt_engine"),
    "prepare_model_artifacts": ("model_artifacts", "prepare_model_artifacts"),
    "OnnxExportResult": ("onnx_export", "OnnxExportResult"),
    "choose_export_dtype": ("onnx_export", "choose_export_dtype"),
    "export_depth_model_onnx": ("onnx_export", "export_depth_model_onnx"),
    "probe_model_dtype": ("onnx_export", "probe_model_dtype"),
    "DepthRuntime": ("runtime", "DepthRuntime"),
    "DepthRuntimeResult": ("runtime", "DepthRuntimeResult"),
    "StereoLabDepthRuntime": ("runtime", "StereoLabDepthRuntime"),
    "StereoLabDepthRuntimeResult": ("runtime", "StereoLabDepthRuntimeResult"),
    "StereoLabRuntime": ("runtime", "StereoLabRuntime"),
    "StereoLabRuntimeResult": ("runtime", "StereoLabRuntimeResult"),
    "StereoRuntime": ("runtime", "StereoRuntime"),
    "StereoRuntimeResult": ("runtime", "StereoRuntimeResult"),
    "StereoConfig": ("synthesis", "StereoConfig"),
    "StereoResult": ("synthesis", "StereoResult"),
    "synthesize_stereo": ("synthesis", "synthesize_stereo"),
    "OpenXREyeView": ("openxr_render", "OpenXREyeView"),
    "OpenXRFov": ("openxr_render", "OpenXRFov"),
    "OpenXRRenderConfig": ("openxr_render", "OpenXRRenderConfig"),
    "OpenXRScreenPose": ("openxr_render", "OpenXRScreenPose"),
    "OpenXRStereoResult": ("openxr_render", "OpenXRStereoResult"),
    "OpenXRRuntimeResult": ("runtime", "OpenXRRuntimeResult"),
    "PARALLAX_RESOLVER_VERSION": ("parallax", "PARALLAX_RESOLVER_VERSION"),
    "ParallaxBudget": ("parallax", "ParallaxBudget"),
    "RuntimeSettingsPipelineRebuildRequired": ("settings_snapshot", "RuntimeSettingsPipelineRebuildRequired"),
    "RuntimeSettingsRestartRequired": ("settings_snapshot", "RuntimeSettingsRestartRequired"),
    "RuntimeSettingsSnapshot": ("settings_snapshot", "RuntimeSettingsSnapshot"),
    "SnapshotChangeClass": ("settings_snapshot", "SnapshotChangeClass"),
    "RenderSizeConfig": ("render_size", "RenderSizeConfig"),
    "RenderSizePolicy": ("render_size", "RenderSizePolicy"),
    "openxr_result_from_stereo_result": ("runtime", "openxr_result_from_stereo_result"),
    "build_openxr_eye_mvp": ("openxr_render", "build_openxr_eye_mvp"),
    "is_pyopenxr_available": ("openxr_render", "is_pyopenxr_available"),
    "render_openxr_stereo": ("openxr_render", "render_openxr_stereo"),
    "resolve_render_size": ("render_size", "resolve_render_size"),
    "runtime_output_size_text": ("render_size", "runtime_output_size_text"),
    "AutoModeDecision": ("presets", "AutoModeDecision"),
    "AutoModeRuntime": ("presets", "AutoModeRuntime"),
    "AutoModeRuntimeState": ("presets", "AutoModeRuntimeState"),
    "AutoModeSignals": ("presets", "AutoModeSignals"),
    "PRESET_CHOICES": ("presets", "PRESET_CHOICES"),
    "StereoModePreset": ("presets", "StereoModePreset"),
    "auto_detection_required": ("presets", "auto_detection_required"),
    "auto_mode_scores": ("presets", "auto_mode_scores"),
    "classify_auto_mode": ("presets", "classify_auto_mode"),
    "openxr_config_for_auto_mode": ("presets", "openxr_config_for_auto_mode"),
    "openxr_config_for_preset": ("presets", "openxr_config_for_preset"),
    "preset_summary": ("presets", "preset_summary"),
    "resolve_parallax_budget": ("parallax", "resolve_parallax_budget"),
    "stereo_config_for_auto_mode": ("presets", "stereo_config_for_auto_mode"),
    "stereo_config_for_preset": ("presets", "stereo_config_for_preset"),
    "VulkanImageCopyPass": ("vulkan_image_pass", "VulkanImageCopyPass"),
    "VulkanStereoFusedParams": ("vulkan_stereo_pass", "VulkanStereoFusedParams"),
    "VulkanStereoFusedPass": ("vulkan_stereo_pass", "VulkanStereoFusedPass"),
    "VulkanLayeredStereoParams": ("vulkan_stereo_pass", "VulkanLayeredStereoParams"),
    "VulkanLayeredStereoPass": ("vulkan_stereo_pass", "VulkanLayeredStereoPass"),
    "VulkanStereoComputeBackend": ("vulkan_backend", "VulkanStereoComputeBackend"),
    "VulkanStereoImageComputeBackend": ("vulkan_backend", "VulkanStereoImageComputeBackend"),
    "VulkanStereoBackendUnavailable": ("vulkan_backend", "VulkanStereoBackendUnavailable"),
    "NVIDIA_VENDOR_ID": ("compute_backend", "NVIDIA_VENDOR_ID"),
    "StereoComputeBackend": ("compute_backend", "StereoComputeBackend"),
    "StereoComputeBackendUnavailable": ("compute_backend", "StereoComputeBackendUnavailable"),
    "resolve_stereo_compute_backend": ("compute_backend", "resolve_stereo_compute_backend"),
    "TritonRuntimeInfo": ("triton_runtime", "TritonRuntimeInfo"),
    "probe_triton_runtime": ("triton_runtime", "probe_triton_runtime"),
    "triton_runtime_available": ("triton_runtime", "triton_runtime_available"),
    "clear_triton_probe_cache": ("triton_runtime", "clear_triton_probe_cache"),
}


def __getattr__(name: str):
    try:
        module_name, attr_name = _LAZY_EXPORTS[name]
    except KeyError as exc:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from exc
    from importlib import import_module

    module = import_module(f".{module_name}", __name__)
    value = getattr(module, attr_name)
    globals()[name] = value
    return value


__all__ = [
    "AutoModeDecision",
    "AutoModeRuntime",
    "AutoModeRuntimeState",
    "AutoModeSignals",
    "DepthModelSpec",
    "DepthRuntime",
    "DepthRuntimeConfig",
    "DepthRuntimeResult",
    "ModelRegistry",
    "ModelArtifactPaths",
    "OnnxExportResult",
    "OpenXREyeView",
    "OpenXRFov",
    "OpenXRRenderConfig",
    "OpenXRScreenPose",
    "OpenXRRuntimeResult",
    "OpenXRStereoResult",
    "PARALLAX_RESOLVER_VERSION",
    "PRESET_CHOICES",
    "ParallaxBudget",
    "PreparedModelArtifacts",
    "RuntimeSettingsPipelineRebuildRequired",
    "RuntimeSettingsRestartRequired",
    "RuntimeSettingsSnapshot",
    "SnapshotChangeClass",
    "RenderSizeConfig",
    "RenderSizePolicy",
    "StereoConfig",
    "StereoLabDepthRuntime",
    "StereoLabDepthRuntimeConfig",
    "StereoLabDepthRuntimeResult",
    "StereoLabRuntime",
    "StereoLabRuntimeConfig",
    "StereoLabRuntimeResult",
    "StereoModePreset",
    "StereoResult",
    "StereoRuntime",
    "StereoRuntimeConfig",
    "StereoRuntimeResult",
    "VulkanImageCopyPass",
    "VulkanStereoFusedParams",
    "VulkanStereoFusedPass",
    "VulkanLayeredStereoParams",
    "VulkanLayeredStereoPass",
    "VulkanStereoComputeBackend",
    "VulkanStereoImageComputeBackend",
    "VulkanStereoBackendUnavailable",
    "NVIDIA_VENDOR_ID",
    "StereoComputeBackend",
    "StereoComputeBackendUnavailable",
    "resolve_stereo_compute_backend",
    "TritonRuntimeInfo",
    "probe_triton_runtime",
    "triton_runtime_available",
    "clear_triton_probe_cache",
    "artifact_paths_for_model",
    "auto_detection_required",
    "auto_mode_scores",
    "build_openxr_eye_mvp",
    "choose_export_dtype",
    "classify_auto_mode",
    "depth_provider_config_from_runtime",
    "ensure_model_downloaded",
    "ensure_onnx_exported",
    "ensure_tensorrt_engine",
    "export_depth_model_onnx",
    "is_pyopenxr_available",
    "openxr_config_for_auto_mode",
    "openxr_config_for_preset",
    "openxr_result_from_stereo_result",
    "preset_for_runtime_mode",
    "preset_summary",
    "prepare_model_artifacts",
    "resolve_parallax_budget",
    "probe_model_dtype",
    "render_openxr_stereo",
    "resolve_render_size",
    "resolve_model_dir",
    "runtime_frame_contract",
    "runtime_config_from_d2s_settings",
    "runtime_output_size_text",
    "stereo_config_for_auto_mode",
    "stereo_config_for_preset",
    "stereo_config_from_runtime",
    "synthesize_stereo",
]
